import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk, Outfit } from "next/font/google";
import "./globals.css";

const geistOutfit = Outfit({
    variable: "--font-geist-outfit",
    subsets: ["latin"],
});

const geistSpaceGrotesk = Space_Grotesk({
    variable: "--font-geist-space-grotesk",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                data-page={children.props.page || "default"}
                className={`${geistOutfit.variable} ${geistSpaceGrotesk.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
